/// Computes the sum of all even Fibonacci numbers up to a given limit.
///
/// The Fibonacci sequence starts with 1 and 2 in this implementation, and each
/// subsequent value is generated by summing the previous two. The function
/// iterates through the sequence, adding each even-valued term to an
/// accumulator until the next Fibonacci number would exceed `limit`.
///
/// # Arguments
/// * `limit` — The maximum Fibonacci value to include in the sum.
///
/// # Returns
/// The total sum of all even Fibonacci numbers less than or equal to `limit`.
///
/// # Examples
/// ```
/// let result = even_fib_sum(10);
/// assert_eq!(result, 10); // even Fibonacci numbers ≤ 10 are 2 and 8
/// ```

pub fn even_fib_sum(limit: i128) -> i128 {
    let mut sum: i128 = 0;

    // Starting fib with a=1, b=2
    let mut a = 1;
    let mut b = 2;

    while b <= limit {
        if b % 2 == 0 {
            sum += b;
        }

        let next = a + b;
        a = b;
        b = next;
    }
    sum
}
